import { VibesQuestion } from "./types";

export const VIBES_QUESTION_LIBRARY: VibesQuestion[] = [
  // VIBE_ESENCIA
  {
    id: "CORE-ESENCIA-1",
    category: "VIBE_ESENCIA",
    categoryLabel: "VIBE ESENCIA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene:
      "Desayuno tardío en un cámping de reality: cámara en tu cara, cafetera chilla y las compis en bata de lentejuelas.",
    text: "¿Cómo entro en modo protagonista cuando amanece el campamento?",
    options: [
      { id: "A", label: "Medito con mate y brisa fresca, cero prisa.", mood: "CHILL" },
      { id: "B", label: "Lanzo chisme rápido en stories para activar el salseo.", mood: "SPICY" },
      { id: "C", label: "Pongo bata de satén y saludo como si fuera la presentadora.", mood: "DLUXE" },
      {
        id: "D",
        label: "Bajo al colmado de la plaza en chándal brillante a por pan y mirada.",
        mood: "URBAN",
      },
      { id: "E", label: "Grabo mi propio opening con filtros y humo imaginario.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-ESENCIA-2",
    category: "VIBE_ESENCIA",
    categoryLabel: "VIBE ESENCIA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene:
      "Plano confesionario: luces fucsia, purpurina en el aire y un micro que pide storytime.",
    text: "Cuando me preguntan quién soy, ¿qué mood saco primero?",
    options: [
      { id: "A", label: "Soy chill, team manta y té, pero con chispa sutil.", mood: "CHILL" },
      { id: "B", label: "Soy picante, reina del comeback y del emoji con fueguito.", mood: "SPICY" },
      { id: "C", label: "Soy deluxe, brillo hasta en pijama y hago entrance.", mood: "DLUXE" },
      {
        id: "D",
        label: "Soy calle glam: acento de barrio, aro dorado y coreo en la acera.",
        mood: "URBAN",
      },
      { id: "E", label: "Soy collage: mezclo referencias random y me queda arte.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-ESENCIA-3",
    category: "VIBE_ESENCIA",
    categoryLabel: "VIBE ESENCIA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene:
      "After de karaoke clandestino en una piscina hinchable, alguien pide tu canción insignia.",
    text: "¿Cuál es mi mood cuando necesito recargar batería emocional?",
    options: [
      { id: "A", label: "Me tiro en hamaca, playlist lofi y dejo que pase el mundo.", mood: "CHILL" },
      { id: "B", label: "Busco drama catártico en TikTok y comento con ironía.", mood: "SPICY" },
      { id: "C", label: "Spa casero con velas, mascarilla dorada y bata fluff.", mood: "DLUXE" },
      {
        id: "D",
        label: "Paseo por el barrio con gafas grandes, saludo al kiosko y pillo churro.",
        mood: "URBAN",
      },
      { id: "E", label: "Pinto, escribo o bailo algo rarísimo hasta sentirme persona.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-ESENCIA-4",
    category: "VIBE_ESENCIA",
    categoryLabel: "VIBE ESENCIA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Noche de gala cutre en el patio del camp, alfombra de césped y flashes de móviles.",
    text: "¿Cómo anuncio que hoy YO llevo la trama principal?",
    options: [
      { id: "A", label: "Levanto ceja, sonrío y dejo que me sigan sin prisa.", mood: "CHILL" },
      { id: "B", label: "Entro con frase incendiaria tipo: ‘Paren todo, tengo update’.", mood: "SPICY" },
      { id: "C", label: "Hago entrada lenta con ventilador portátil y glitter.", mood: "DLUXE" },
      {
        id: "D",
        label: "Llego en patín prestado desde la plaza, con altavoz de reggaetón.",
        mood: "URBAN",
      },
      { id: "E", label: "Monto un mini-performance y dejo pistas visuales.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-ESENCIA-5",
    category: "VIBE_ESENCIA",
    categoryLabel: "VIBE ESENCIA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Fogata camp, termo de chocolate y la cámara te pide un brindis de cierre de jornada.",
    text: "Al final del día, ¿cómo bajo el telón?",
    options: [
      { id: "A", label: "Silencio, mantita y estrellas, cero drama.", mood: "CHILL" },
      { id: "B", label: "Recuento de highlights con risas y audios largos.", mood: "SPICY" },
      { id: "C", label: "Brindo con copa de algo fancy y agradezco como en un premio.", mood: "DLUXE" },
      {
        id: "D",
        label: "Pongo silla en la acera, saco pipas y cuento el día a la vecindad.",
        mood: "URBAN",
      },
      { id: "E", label: "Hago collage de recuerdos en mi libreta brillante.", mood: "ARTSY" },
    ],
  },
  // VIBE_SOCIAL
  {
    id: "CORE-SOCIAL-1",
    category: "VIBE_SOCIAL",
    categoryLabel: "VIBE SOCIAL™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene:
      "Cena de amigas que parece gala de OT en un Mercadona cerrado, focos improvisados con linternas.",
    text: "¿Qué papel tomo en la mesa larga del salseo?",
    options: [
      { id: "A", label: "Soy quien reparte calma y servilletas, vibra zen.", mood: "CHILL" },
      { id: "B", label: "Llevo el hilo del drama y pregunto sin miedo.", mood: "SPICY" },
      { id: "C", label: "Soy host de lujo, sirvo copas y marco protocolo fashion.", mood: "DLUXE" },
      {
        id: "D",
        label: "Saco altavoz con dembow, canto y chasqueo como en plaza en fiestas.",
        mood: "URBAN",
      },
      { id: "E", label: "Anoto frases icónicas para hacer zine después.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SOCIAL-2",
    category: "VIBE_SOCIAL",
    categoryLabel: "VIBE SOCIAL™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Backstage de una gala con brilli-brilli barato y fans con cartulinas DIY.",
    text: "Cuando alguien nuevo entra al grupo, ¿cómo le doy la bienvenida?",
    options: [
      { id: "A", label: "Le doy espacio, sonrisa cálida y tour tranquilo.", mood: "CHILL" },
      { id: "B", label: "Lanzo bromas, le testeo vibes y veo si aguanta el shade.", mood: "SPICY" },
      { id: "C", label: "Le preparo foto glam y le enseño su marca de cámara.", mood: "DLUXE" },
      {
        id: "D",
        label: "Lo llevo al banco de la plaza, birra en mano, que conozca al barrio.",
        mood: "URBAN",
      },
      { id: "E", label: "Le escribo un nickname artístico y le hago sticker.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SOCIAL-3",
    category: "VIBE_SOCIAL",
    categoryLabel: "VIBE SOCIAL™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Rodaje de mini reality en la piscina hinchable, alguien pide dinámica grupal.",
    text: "¿Cuál es mi plan social perfecto un domingo resacoso?",
    options: [
      { id: "A", label: "Picnic suave, pelis malas y cero presión.", mood: "CHILL" },
      { id: "B", label: "Recap del after con memes y bromas internas.", mood: "SPICY" },
      { id: "C", label: "Brunch aesthetic con croissant ridículamente grande.", mood: "DLUXE" },
      {
        id: "D",
        label: "Plaza, bancos calientes, vermú barato y look sport-fashion.",
        mood: "URBAN",
      },
      { id: "E", label: "Mercadillo de arte o expo rara para comentar cada pieza.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SOCIAL-4",
    category: "VIBE_SOCIAL",
    categoryLabel: "VIBE SOCIAL™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Ensayo general de coreografía camp en el comedor, sillas apiladas y lentejuelas sueltas.",
    text: "Si el grupo discute, ¿qué hago yo?",
    options: [
      { id: "A", label: "Propongo respiración y abrazo grupal, paz y amor.", mood: "CHILL" },
      { id: "B", label: "Lanzo frase picante para que se sinceren rápido.", mood: "SPICY" },
      { id: "C", label: "Organizo ronda con copas bonitas y turnos de palabra.", mood: "DLUXE" },
      {
        id: "D",
        label: "Pongo bocina con reggaetón, corto la tensión y saco a bailar en la acera.",
        mood: "URBAN",
      },
      { id: "E", label: "Hago cartelitos con roles y convierto la bronca en performance.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SOCIAL-5",
    category: "VIBE_SOCIAL",
    categoryLabel: "VIBE SOCIAL™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Reunión nocturna en cabaña, micro abierto para confesiones y glitter en la mesa.",
    text: "Cuando alguien me busca consejo sentimental, ¿cómo respondo?",
    options: [
      { id: "A", label: "Escucho, abrazo y recomiendo siesta emocional.", mood: "CHILL" },
      { id: "B", label: "Pregunto todo y suelto verdad con humor picante.", mood: "SPICY" },
      { id: "C", label: "Monto consultorio deluxe con velas, tisana y playlist suave.", mood: "DLUXE" },
      {
        id: "D",
        label: "Doy consejo práctico de barrio: ‘hazlo simple, vámonos a la plaza’.",
        mood: "URBAN",
      },
      { id: "E", label: "Escribo su dilema en papel, lo doblamos y lo quemamos dramáticamente.", mood: "ARTSY" },
    ],
  },
  // VIBE_DRAMA
  {
    id: "CORE-DRAMA-1",
    category: "VIBE_DRAMA",
    categoryLabel: "VIBE DRAMA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Pasillo del camp iluminado en rojo, suena alarma de chisme: alguien lloró en confesionario.",
    text: "¿Qué hago cuando huelo drama fresquito en el grupo?",
    options: [
      { id: "A", label: "Observo desde la hamaca y dejo que se resuelva solo.", mood: "CHILL" },
      { id: "B", label: "Entro con palomitas y preguntas punzantes, modo presentadora.", mood: "SPICY" },
      { id: "C", label: "Ofrezco suite de paz con snacks fancy y charla calmada.", mood: "DLUXE" },
      {
        id: "D",
        label: "Bajo a la plaza a por opiniones y vuelvo con titulares callejeros.",
        mood: "URBAN",
      },
      { id: "E", label: "Transformo el drama en escena teatral improvisada.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-DRAMA-2",
    category: "VIBE_DRAMA",
    categoryLabel: "VIBE DRAMA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Cámara te sigue por el pasillo, alguien te deja en visto tres días y huele a giro de guion.",
    text: "¿Cómo reacciono cuando me clavan un ghosting suave?",
    options: [
      { id: "A", label: "Respiro, suelto y sigo con mi playlist chill.", mood: "CHILL" },
      { id: "B", label: "Mando meme sarcástico y sigo con mi vida, que arda.", mood: "SPICY" },
      { id: "C", label: "Me regalo flores, me arreglo y doy lección de clase.", mood: "DLUXE" },
      {
        id: "D",
        label: "Voy al bar de la esquina, lo cuento con risas y vuelvo brillando.",
        mood: "URBAN",
      },
      { id: "E", label: "Escribo poema o reel dramático con luces de neón.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-DRAMA-3",
    category: "VIBE_DRAMA",
    categoryLabel: "VIBE DRAMA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "El presentador anuncia ‘juego de la verdad’ con micrófonos de juguete y público de peluche.",
    text: "Si alguien me critica en off, ¿qué hago en el siguiente confesionario?",
    options: [
      { id: "A", label: "Sonrío, digo que todo bien y sigo con mi vibe zen.", mood: "CHILL" },
      { id: "B", label: "Tiro shade elegante y dejo claro que me enteré.", mood: "SPICY" },
      { id: "C", label: "Agradezco el feedback con voz de reina y me doy brillo extra.", mood: "DLUXE" },
      {
        id: "D",
        label: "Cuento la historia en la esquina del colmado, con gestos y risas.",
        mood: "URBAN",
      },
      { id: "E", label: "Hago performance de monólogo y dejo mensaje artístico.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-DRAMA-4",
    category: "VIBE_DRAMA",
    categoryLabel: "VIBE DRAMA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Noche de tormenta fake con ventiladores, alguien rompe a llorar en pasarela de cartón.",
    text: "¿Cómo consuelo cuando alguien se desarma delante mío?",
    options: [
      { id: "A", label: "Abrazo, mantita y silencio cuidadoso.", mood: "CHILL" },
      { id: "B", label: "Hago bromita tierna para secar lágrimas y subir mood.", mood: "SPICY" },
      { id: "C", label: "Sirvo té en taza bonita y le doy mi corona simbólica.", mood: "DLUXE" },
      {
        id: "D",
        label: "Le saco a airearse por el barrio, con música de altavoz.",
        mood: "URBAN",
      },
      { id: "E", label: "Propongo dibujar el drama y quemar el papel juntas.", mood: "ARTSY" },
    ],
  },
  // VIBE_SECRETA
  {
    id: "CORE-SECRETA-1",
    category: "VIBE_SECRETA",
    categoryLabel: "VIBE SECRETA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene:
      "Tienda de campaña rosa con letrero de ‘Secret Room’, luces de navidad parpadeando a lo Hannah Montana.",
    text: "¿Qué plan secreto me da paz instantánea?",
    options: [
      { id: "A", label: "Leer fanfics suaves con infusión, nadie molesta.", mood: "CHILL" },
      { id: "B", label: "Stalkear crushes y mandar memes conspirativos.", mood: "SPICY" },
      { id: "C", label: "Spa nocturno con mascarilla de oro y playlist de diva.", mood: "DLUXE" },
      {
        id: "D",
        label: "Ir al 24h de la esquina, comprar chuches y charlar con la cajera.",
        mood: "URBAN",
      },
      { id: "E", label: "Editar vídeos raros que solo entiendo yo.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SECRETA-2",
    category: "VIBE_SECRETA",
    categoryLabel: "VIBE SECRETA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Cabina de grabación improvisada con cojines, cámara en modo confidencial.",
    text: "Cuando tengo crush, ¿qué micro gesto me delata?",
    options: [
      { id: "A", label: "Sonrío bajito y mando sticker tierno.", mood: "CHILL" },
      { id: "B", label: "Lanzo broma subida de tono pero cute.", mood: "SPICY" },
      { id: "C", label: "Le hago regalo pequeño pero ultra cuidado.", mood: "DLUXE" },
      {
        id: "D",
        label: "Le invito a paseo por el barrio, mostrando mis spots secretos.",
        mood: "URBAN",
      },
      { id: "E", label: "Le paso playlist y collage visual que hice pensando en nosotrxs.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SECRETA-3",
    category: "VIBE_SECRETA",
    categoryLabel: "VIBE SECRETA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Guardas un cofre glitter bajo la cama del camp; la cámara te pide abrirlo en directo.",
    text: "¿Cuál es mi guilty pleasure que siempre niego en público?",
    options: [
      { id: "A", label: "Realitys de reformas mientras como galletas.", mood: "CHILL" },
      { id: "B", label: "Reels de salseo y teorías conspiranoicas.", mood: "SPICY" },
      { id: "C", label: "Comprar cosas shiny que no necesito, pero lookean.", mood: "DLUXE" },
      {
        id: "D",
        label: "Bailar en la plaza con temazos viejos de barrio, sin vergüenza.",
        mood: "URBAN",
      },
      { id: "E", label: "Coleccionar entradas de cine y pegarlas en cuadernos arty.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-SECRETA-4",
    category: "VIBE_SECRETA",
    categoryLabel: "VIBE SECRETA™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Luces bajas en la cocina del camp, midnight snack y confesiones en calcetines de purpurina.",
    text: "¿Qué hago cuando nadie mira y necesito mini subidón?",
    options: [
      { id: "A", label: "Bailo suave con cascos y canto bajito.", mood: "CHILL" },
      { id: "B", label: "Ensayo respuestas dramáticas frente al espejo.", mood: "SPICY" },
      { id: "C", label: "Me pongo perfume caro y labial aunque sea para ir a la nevera.", mood: "DLUXE" },
      {
        id: "D",
        label: "Hago coreo de trap en la terraza mirando la calle.",
        mood: "URBAN",
      },
      { id: "E", label: "Pinto rayas y stickers en mi diario como si fuera mural.", mood: "ARTSY" },
    ],
  },
  // VIBE_CAOS
  {
    id: "CORE-CAOS-1",
    category: "VIBE_CAOS",
    categoryLabel: "VIBE CAOS™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Prueba de campamento: rueda inflable gigante, megáfono y presentador disfrazado de drag pirata.",
    text: "Si aparece un plot twist absurdo, ¿cómo lo abrazo?",
    options: [
      { id: "A", label: "Me río, respiro y fluyo sin despeinarme.", mood: "CHILL" },
      { id: "B", label: "Hago comentario ácido y me subo al caos con glitter.", mood: "SPICY" },
      { id: "C", label: "Convierto el caos en pasarela, pose y foto.", mood: "DLUXE" },
      {
        id: "D",
        label: "Armo equipo improvisado con la gente de la plaza, modo comando callejero.",
        mood: "URBAN",
      },
      { id: "E", label: "Lo convierto en corto experimental con filtros locos.", mood: "ARTSY" },
    ],
  },
  {
    id: "CORE-CAOS-2",
    category: "VIBE_CAOS",
    categoryLabel: "VIBE CAOS™",
    packId: "CORE_VIBES",
    spicyLevel: "SOFT",
    scene: "Final de temporada: lluvia de confeti barato, DJ borroso y la organización anuncia reto sorpresa.",
    text: "¿Qué hago cuando todo sale al revés en el último minuto?",
    options: [
      { id: "A", label: "Acepto el plot, improviso y me quedo chill.", mood: "CHILL" },
      { id: "B", label: "Suelto risas, shade y giro el guion a mi favor.", mood: "SPICY" },
      { id: "C", label: "Saco plan B con glamour y sonrisa de finalista.", mood: "DLUXE" },
      {
        id: "D",
        label: "Llamo a la crew del barrio, montamos plan relámpago en la calle.",
        mood: "URBAN",
      },
      { id: "E", label: "Improviso arte: cartelones, coreo rara y lo hago memorable.", mood: "ARTSY" },
    ],
  },
];
